CREATE DATABASE IF NOT EXISTS cisc3003_paper02_b CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cisc3003_paper02_b;

CREATE TABLE IF NOT EXISTS contact_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender_name VARCHAR(120) NOT NULL,
    sender_email VARCHAR(160) NOT NULL,
    subject VARCHAR(160) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
